[project]
name = "climax-prompt"
version = "0.5.4"
description = "Prompt for input via the CLI."
authors = [
    {name = "Snap",email = "XxSnapperGeexX@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE.txt"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "mypy (>=2.3.1,<3.0.0)",
    "sphinx (>=9.1.0,<10.0.0)",
    "numpydoc (>=1.10.0,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "furo (>=2025.12.19,<2026.0.0)",
    "ruff (>=0.16.5,<0.17.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytest-html (>=4.2.0,<5.0.0)",
]

[project.urls]
documentation = "https://snap-climax.gitlab.io/python-prompt/"
homepage = "https://gitlab.com/snap-climax/python-prompt"
issues = "https://gitlab.com/snap-climax/python-prompt/-/issues"
repository = "https://gitlab.com/snap-climax/python-prompt"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "climax/prompt", from = "src/main"}]

[tool.pytest]
testpaths = ["src/test"]
addopts = ["--import-mode=importlib"]

[tool.mypy]
files = ["src"]
strict = true
mypy_path = ["src/main"]
explicit_package_bases = true
enable_error_code = ["redundant-expr"]

[tool.tox]
requires = ["tox>=4.61", "tox-uv>=1.36"]
env_list = [
    { prefix = "py3", start = 13, stop = 14 },
    { prefix = "mypy-py3", start = 13, stop = 14 }
]

[tool.tox.env_run_base]
package = "skip"
set_env = { POETRY_VIRTUALENVS_CREATE = "false", PYTEST_ADDOPTS = "--junit-prefix={env_name}" }
allowlist_externals = ["make"]
deps = ["poetry"]
commands_pre = [["poetry", "install"]]

[tool.tox.env.py314]
base_python = ["3.14"]
commands = [["make", "test-xml"]]

[tool.tox.env.py313]
base_python = ["3.13"]
commands = [
    [
        "make",
        "test-xml",
        "TESTRESULTSDIR=build/test/results/py313",
    ],
]

[tool.tox.env.mypy-py314]
base_python = ["3.14"]
commands = [["make", "mypy"]]

[tool.tox.env.mypy-py313]
base_python = ["3.13"]
commands = [["make", "mypy"]]

[tool.coverage.run]
source = ["src/main"]
data_file = "build/test/coverage/.coverage"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["C4", "I", "PT", "TC", "RET"]
